-- MySQL Script generated by MySQL Workbench
-- Mon 29 Feb 2016 10:15:42 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema steam
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `steam` ;

-- -----------------------------------------------------
-- Schema steam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `steam` DEFAULT CHARACTER SET utf8 ;
USE `steam` ;

-- -----------------------------------------------------
-- Table `steam`.`steam_price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steam`.`steam_price` ;

CREATE TABLE IF NOT EXISTS `steam`.`steam_price` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `price` DECIMAL(6,2) NULL,
  `review` INT NULL,
  `time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
